---
cert: /path/to/cert.crt
key: /path/to/key.crt
ca: /path/to/ca.crt
actions:
  - name: Do Something
    precommand:
      - /do/something first
    cert: /copy/to/cert.crt
    key: /copy/top/key.crt
    fullchain: /copy/to/fullchain.crt
    postcommand: 
      - /run/something someargument
      - /run/something/else
